apiVersion: v1
kind: Service
metadata:
    name: donation-form
    labels: &labels
        app.kubernetes.io/name: donation-form
spec:
    selector: *labels
    ports:
        - name: http
          port: 80
          targetPort: http